[package]
name = "echo-loop-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"

[dependencies]
serde_json = "1"
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "dsh:echo-loop"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"dsh:dsh" = { path = "../../crates/dsh-wasmrt/wit-dsh" }
"dsh:plugin" = { path = "../../crates/dsh-wasmrt/wit" }

[workspace]
