// D-210 S5：Rust 壳发布产物（canvas-shell bindgen 输出）编译期内嵌表。
// 扫描 assets/canvas-shell/**.{js,wasm,html} → OUT_DIR/shell_assets.rs（include_bytes!）。
// 产物更新流程：canvas-shell/build.ps1 → 拷贝 dist-release/* 入 assets/canvas-shell/ → 本表自动刷新。
use std::{env, fs, path::{Path, PathBuf}};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let base = manifest.join("assets").join("canvas-shell");
    println!("cargo:rerun-if-changed=assets/canvas-shell");
    println!("cargo:rerun-if-changed=build.rs");

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if base.is_dir() {
        walk(&base, &base, &mut files);
    }
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — Rust 壳资产内嵌表（D-210 S5）。勿手改。\n\
         pub static SHELL_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (rel, p) in &files {
        out.push_str(&format!(
            "    (\"{rel}\", include_bytes!(r#\"{}\"#)),\n",
            p.display()
        ));
    }
    out.push_str("];\n");
    fs::write(Path::new(&env::var("OUT_DIR").unwrap()).join("shell_assets.rs"), out).unwrap();
}

fn walk(dir: &Path, base: &Path, out: &mut Vec<(String, PathBuf)>) {
    for e in fs::read_dir(dir).unwrap() {
        let p = e.unwrap().path();
        if p.is_dir() {
            walk(&p, base, out);
            continue;
        }
        let ext = p.extension().and_then(|x| x.to_str()).unwrap_or("");
        if matches!(ext, "js" | "wasm" | "html") {
            let rel = p.strip_prefix(base).unwrap().to_string_lossy().replace('\\', "/");
            out.push((rel, p));
        }
    }
}
