// D-210 S5：Rust 壳发布产物（canvas-shell bindgen 输出）编译期内嵌表。
// 扫描 assets/canvas-shell/**.{js,wasm,html} → OUT_DIR/shell_assets.rs（include_bytes!）。
// S5 尾项：每件同时产出 gzip 预压缩件（Level::best，纯 Rust 后端）→ 三元组表
// (rel, raw, gz)；运行时按 Accept-Encoding 协商（canvas_response_enc）。
// 产物更新流程：canvas-shell/build.ps1 → 拷 dist-release/*（先清中间件）入
// assets/canvas-shell/ → 本表自动刷新。
use flate2::{write::GzEncoder, Compression};
use std::{env, fs, io::Write, path::{Path, PathBuf}};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let base = manifest.join("assets").join("canvas-shell");
    println!("cargo:rerun-if-changed=assets/canvas-shell");
    println!("cargo:rerun-if-changed=build.rs");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if base.is_dir() {
        walk(&base, &base, &mut files);
    }
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — Rust 壳资产内嵌表（D-210 S5 + gzip 预压缩）。勿手改。\n\
         pub static SHELL_ASSETS: &[(&str, &[u8], &[u8])] = &[\n",
    );
    for (rel, p) in &files {
        let raw = fs::read(p).unwrap();
        let mut enc = GzEncoder::new(Vec::new(), Compression::best());
        enc.write_all(&raw).unwrap();
        let gz = enc.finish().unwrap();
        let gz_path = out_dir.join(rel.replace('/', "__") + ".gz");
        fs::write(&gz_path, &gz).unwrap();
        out.push_str(&format!(
            "    (\"{rel}\", include_bytes!(r#\"{}\"#), include_bytes!(r#\"{}\"#)),\n",
            p.display(),
            gz_path.display()
        ));
    }
    out.push_str("];\n");
    fs::write(out_dir.join("shell_assets.rs"), out).unwrap();
}

fn walk(dir: &Path, base: &Path, out: &mut Vec<(String, PathBuf)>) {
    for e in fs::read_dir(dir).unwrap() {
        let p = e.unwrap().path();
        if p.is_dir() {
            walk(&p, base, out);
            continue;
        }
        let ext = p.extension().and_then(|x| x.to_str()).unwrap_or("");
        if matches!(ext, "js" | "wasm" | "html") {
            let rel = p.strip_prefix(base).unwrap().to_string_lossy().replace('\\', "/");
            out.push((rel, p));
        }
    }
}
